version: "3.4"
services:

  microservice:
    restart: always
    build:
      dockerfile: ./Dockefile
      context: ./app/
      target: development
    command: npm run start:debug
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - microservice
    ports: # HOST:CONTAINER
      - 9229:9229
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:12-alpine
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "Authentication"
      POSTGRES_USER: "microservice"
      POSTGRES_PASSWORD: "m*3TN4ATqMXM#VQtsCDKm4W@zKm+pDLr"
    networks:
      - microservice
      - database
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/postgresql/data

  admin-panel:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - database

networks:
  microservice:
  database:

volumes:
  dbdata:
