version: "3.4"
services:
  #
  # [ server stack ]
  #
  web-server:
    restart: on-failure
    build:
      context: ./app/
      target: production
    networks:
      - service
    ports: # HOST:CONTAINER
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - service
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - databases:/var/lib/mysql

#
# [ volumes definition ]
#
# creates Docker volumes which can be mounted by other containers too e.g. for backup
#
volumes:
  databases:
    driver: local

#
# [ networks definition ]
#
networks:
  service:
    driver: bridge
